# Generated by Django 4.0.1 on 2022-01-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('noob', 'Noob'), ('elite', 'Elite'), ('admin', 'Admin')], default='noob', max_length=6),
        ),
    ]
